import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [formData, setFormData] = useState({ email: "" });

  const handleInput = e => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = e => {
    e.preventDefault();
    console.log("this would call api endpoint");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Minified React error with simple form</h1>
        <p>
          This is a super simple, normal form with an email input and
          placeholder value. In the project I encountered this issue I have
          proper endpoint to handle the submission, etc. However, its actually
          not necessary to show that by simply placing a placeholder value this
          causes the &apos;Uncaught Error: Minified React error #425&apos; once
          deployed on Vercel.
        </p>
        <form>
          <input
            type="email"
            name="email"
            id="email"
            placeholder="Enter your email"
          />
        </form>
      </main>
    </>
  );
}
